/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GestionMaquinas.java
 *
 * Created on 11-23-2011, 08:04:41 AM
 */
package mi.Calendario;
import java.util.*;
import javax.swing.JOptionPane;
/**
 *
 * @author r.marin
 */
public class GestionMaquinas extends javax.swing.JFrame{
    private Maquina elemento;
    private EscribirLeerListas docs;
    private ArrayList combinacion;
    /** Creates new form GestionMaquinas */
    public GestionMaquinas() {
        initComponents();
        combinacion = new ArrayList(24); 
        elemento = new Maquina();
        docs = new EscribirLeerListas(); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Tabs = new javax.swing.JTabbedPane();
        AgrMaquina = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        cod = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        prd = new javax.swing.JComboBox();
        salir = new javax.swing.JButton();
        BusqMaquina = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        codBuscar = new javax.swing.JTextField();
        nomResult = new javax.swing.JTextField();
        prdResult = new javax.swing.JTextField();
        salirBusq = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        editar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Gestion Máquinas Matenimiento Nivel 1");

        Tabs.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        AgrMaquina.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Código de máquina");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("Nombre de máquina");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText("Prioridad");

        agregar.setFont(new java.awt.Font("Tahoma", 1, 11));
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        borrar.setFont(new java.awt.Font("Tahoma", 1, 11));
        borrar.setText("Borrar");
        borrar.setMaximumSize(new java.awt.Dimension(79, 23));
        borrar.setMinimumSize(new java.awt.Dimension(79, 23));
        borrar.setPreferredSize(new java.awt.Dimension(79, 23));
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        prd.setFont(new java.awt.Font("Tahoma", 1, 11));
        prd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C" }));
        prd.setMinimumSize(new java.awt.Dimension(23, 18));
        prd.setPreferredSize(new java.awt.Dimension(28, 20));

        salir.setFont(new java.awt.Font("Tahoma", 1, 11));
        salir.setText("Salir y Actualizar");
        salir.setMaximumSize(new java.awt.Dimension(79, 23));
        salir.setMinimumSize(new java.awt.Dimension(79, 23));
        salir.setPreferredSize(new java.awt.Dimension(79, 23));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgrMaquinaLayout = new javax.swing.GroupLayout(AgrMaquina);
        AgrMaquina.setLayout(AgrMaquinaLayout);
        AgrMaquinaLayout.setHorizontalGroup(
            AgrMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgrMaquinaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AgrMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgrMaquinaLayout.createSequentialGroup()
                        .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AgrMaquinaLayout.createSequentialGroup()
                        .addGroup(AgrMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(35, 35, 35)
                        .addGroup(AgrMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cod)
                            .addComponent(nom)
                            .addComponent(prd, 0, 134, Short.MAX_VALUE))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        AgrMaquinaLayout.setVerticalGroup(
            AgrMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgrMaquinaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(AgrMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(AgrMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgrMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(prd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(AgrMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar)
                    .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        Tabs.addTab("Agregar Máquina", AgrMaquina);

        BusqMaquina.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setText("Código a buscar");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setText("Nombre de máquina");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setText("Prioridad de máquina");

        nomResult.setEditable(false);

        prdResult.setEditable(false);

        salirBusq.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        salirBusq.setText("Salir");
        salirBusq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBusqActionPerformed(evt);
            }
        });

        buscar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        eliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        editar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BusqMaquinaLayout = new javax.swing.GroupLayout(BusqMaquina);
        BusqMaquina.setLayout(BusqMaquinaLayout);
        BusqMaquinaLayout.setHorizontalGroup(
            BusqMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BusqMaquinaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BusqMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BusqMaquinaLayout.createSequentialGroup()
                        .addGroup(BusqMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addGroup(BusqMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prdResult, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(nomResult)
                            .addComponent(codBuscar))
                        .addGap(76, 76, 76))
                    .addGroup(BusqMaquinaLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addGap(276, 276, 276))
                    .addGroup(BusqMaquinaLayout.createSequentialGroup()
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editar, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(salirBusq, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(116, 116, 116))
        );
        BusqMaquinaLayout.setVerticalGroup(
            BusqMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BusqMaquinaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(BusqMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(codBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BusqMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nomResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BusqMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(prdResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BusqMaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salirBusq))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        Tabs.addTab("Buscar Máquina", BusqMaquina);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(174, 174, 174))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        String codTemp = cod.getText();
        String nomTemp = nom.getText();
        String prTemp =  (String) prd.getSelectedItem();
        
        if(nomTemp.equals("") || codTemp.equals("")){
            JOptionPane.showMessageDialog(null, "Error: Nombre o Código en blanco", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            elemento.setTodo(codTemp, nomTemp, prTemp);
            if(!docs.revisarDuplicado(elemento)){
                if (docs.agregarMaquina(elemento)){
                    JOptionPane.showMessageDialog(null, "Éxito: Máquina Agregada", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Error al agregar máquina", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            else{
               JOptionPane.showMessageDialog(null, "Código Duplicado: La máquina ya existe", "Mensaje", JOptionPane.INFORMATION_MESSAGE); 
            }
        }
    }//GEN-LAST:event_agregarActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        nom.setText("");
        cod.setText("");
    }//GEN-LAST:event_borrarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        if(docs.escribirLista()){
            JOptionPane.showMessageDialog(null, "Escritura de máquinas completada!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void salirBusqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBusqActionPerformed
        if(docs.escribirLista()){
            JOptionPane.showMessageDialog(null, "Escritura de máquinas completada!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
        System.exit(0);
    }//GEN-LAST:event_salirBusqActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(docs.escribirLista()){
            JOptionPane.showMessageDialog(null, "Escritura de máquinas completada!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        String codTemp = codBuscar.getText();
        if(codTemp.equals("")){
            JOptionPane.showMessageDialog(null, "Error: Código en blanco", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            Maquina buscada = docs.buscarMaquina(codTemp);
            if(buscada != null){
                JOptionPane.showMessageDialog(null, "¡Máquina encontrada!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                nomResult.setText(buscada.getNombre());
                prdResult.setText(buscada.getPrioridad());
            }
            else{
                JOptionPane.showMessageDialog(null, "Código incorrecto, tal máquina no existe.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                nomResult.setText("");
                prdResult.setText("");
            }
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        String codTemp = codBuscar.getText();
        if(codTemp.equals("")){
            JOptionPane.showMessageDialog(null, "Error: Código en blanco", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            Maquina buscada = docs.buscarMaquina(codTemp);
            if(buscada != null){
                nomResult.setText(buscada.getNombre());
                prdResult.setText(buscada.getPrioridad());
                //Falta confirmación por parte del usuario
                if(docs.eliminarMaquina(buscada)){
                    JOptionPane.showMessageDialog(null, "Máquina eliminada con éxito", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Error: No se pudo eliminar la máquina", "Mensaje", JOptionPane.INFORMATION_MESSAGE); 
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Código incorrecto, tal máquina no existe.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                nomResult.setText("");
                prdResult.setText("");
            }
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        String codTemp = codBuscar.getText();
        if(codTemp.equals("")){
            JOptionPane.showMessageDialog(null, "Error: Código en blanco", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            Maquina buscada = docs.buscarMaquina(codTemp);
            if(buscada != null){
                nomResult.setText(buscada.getNombre());
                prdResult.setText(buscada.getPrioridad());
                docs.editarMaquina(buscada); //Veamos que pasa
            }
            else{
                JOptionPane.showMessageDialog(null, "Código incorrecto, tal máquina no existe.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                nomResult.setText("");
                prdResult.setText("");
            }
        }
    }//GEN-LAST:event_editarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionMaquinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionMaquinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionMaquinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionMaquinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new GestionMaquinas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgrMaquina;
    private javax.swing.JPanel BusqMaquina;
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JButton agregar;
    private javax.swing.JButton borrar;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField cod;
    private javax.swing.JTextField codBuscar;
    private javax.swing.JButton editar;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField nomResult;
    private javax.swing.JComboBox prd;
    private javax.swing.JTextField prdResult;
    private javax.swing.JButton salir;
    private javax.swing.JButton salirBusq;
    // End of variables declaration//GEN-END:variables
}
